CREATE TABLE WALLET_ACCOUNT (USER_DNI VARCHAR(255), JAVA_COINS BIGINT);
CREATE TABLE ORDERS (
    ID BIGINT PRIMARY KEY,
    SELLER_DNI VARCHAR(255),
    BUYER_DNI VARCHAR(255),
    JAVA_COINS_AMOUNT BIGINT,
    JAVA_COIN_PRICE BIGINT,
    ORDER_STATE VARCHAR(255)
);
